FROM tiangolo/uwsgi-nginx-flask:python3.8

MAINTAINER paulmattingley

ADD requirements.txt /app
RUN pip install -r /app/requirements.txt

COPY /app /app/app
COPY /test /app/test

CMD ["python", "/app/app/main.py" ]