FROM tiangolo/uwsgi-nginx-flask:python3.8

MAINTAINER paulmattingley

ADD requirements.txt /app
COPY /app /app
COPY /test /test

RUN pip install -r /app/requirements.txt

CMD ["python", "/app/main.py" ]